apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-app3
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broken-app3
  template:
    metadata:
      labels:
        app: broken-app3
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: app
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP    
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1  
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 60
